version: '3.4'

services:
  app:
    build:
      context: .
    environment:
      TOKEN: OTEzODYyOTg2NzIzMTI3Mzc2.YaErOg.QXSYKNFuSgleRgMoO-mYi6Zfhjs
      MONGO_DBNAME: warzone-stats
      MONGO_URI: 'mongodb://mongo:27017/?readPreference=primary&appname=MongoDB%20Compass&ssl=false'
    depends_on:
      - mongo

  mongo:
    image: mongo
    restart: always
    ports:
      - '27017:27017'
